spring.application.name=customer-service
server.port = 8081

spring.datasource.url=jdbc:mysql://localhost:3306/dwb_customer_service
spring.datasource.username=root
spring.datasource.password=Hola$123.,
spring.datasource.driverClassName=com.mysql.jdbc.Driver

# Files
app.upload.dir=uploads
app.upload.images=img

# Swagger
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.doc-expansion=none